language: python
python:
  - 2.7
  - 3.2
env:
  - DJANGO=1.7.0
before_install:
  - export DJANGO_SETTINGS_MODULE=nublas.tests.settings
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls
  - pip install .
script:
  - coverage run --timid --source=nublas manage.py test nublas
after_success:
  - coveralls
